export const movies = [
  {
    source: 'https://image.tmdb.org/t/p/w200/unbrtK8zEjPANvNkbwhjpSxYWzN.jpg',
    rating: 5,
    producer: 'prime',
    title: '8888',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 0,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg',
    rating: 4,
    producer: 'prime',
    title: '333',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 1,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/lB068qa6bQ0QKYKyC2xnYGvYjl7.jpg',
    rating: 5,
    producer: 'prime',
    title: '4444',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 2,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg',
    rating: 4,
    producer: 'universal',
    title: '8888',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 3,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/sXK0Wdm4B18o1y39XcizA7K3caC.jpg',
    rating: 5,
    producer: 'universal',
    title: '6',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 4,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/gLhHHZUzeseRXShoDyC4VqLgsNv.jpg',
    rating: 4,
    title: '777',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    producer: 'universal',
    id: 5,
    forYou: false,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg',
    rating: 5,
    producer: 'prime',
    title: '9999',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 6,
    forYou: true,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
    rating: 4,
    producer: 'prime',

    title: '0000',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 7,
    forYou: true,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/bCi2HQ2B9mBknm6LVBPcgOb0Mlg.jpg',
    rating: 5,
    producer: 'prime',
    title: '4343',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 8,
    forYou: true,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/obpPQskaVpSiC9RcJRB6iWDTCXS.jpg',
    rating: 4,
    producer: 'universal',
    title: '5445',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 9,
    forYou: true,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/oVolaz0eIANKuPXhRuX4H5dz0HB.jpg',
    rating: 5,
    producer: 'universal',
    title: '88876768',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 10,
    forYou: true,
  },
  {
    source: 'https://image.tmdb.org/t/p/w200/fxIzSyOMrOFxwCIWIW4bwtgMpds.jpg',
    rating: 4,
    producer: 'universal',
    title: '222288',
    duration: '1 Hour 45 Munites',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eleifend tempor at egestas diam malesuada donec donec. Vestibulum sed euismod purus magna lectus viverra nunc turpis vitae. Morbi nunc ornare pulvinar placerat. Faucibus eget laoreet morbi euismod egestas tempor.',
    actors: ['Zeev revah', 'Yehuda barkan'],
    id: 11,
    forYou: true,
  },
];
